name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/coursier/v1
            ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Set up cert permissions (1)
        run: chmod 600 test-cert/server.key
      - name: Set up cert permissions (2)
        run: sudo chown 999 test-cert/server.key
      - name: Start up Postgres instances
        run: docker-compose up -d
      - name: Compile and test
        run: csbt headerCheck clean +test
      - name: Shut down Postgres instances
        run: docker-compose down
